ALTER TABLE "LiteLLM_DailyUserSpend"
ADD COLUMN "response_time_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "response_time_count" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN "ttft_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ttft_count" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "LiteLLM_DailyOrganizationSpend"
ADD COLUMN "response_time_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "response_time_count" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN "ttft_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ttft_count" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "LiteLLM_DailyEndUserSpend"
ADD COLUMN "response_time_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "response_time_count" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN "ttft_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ttft_count" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "LiteLLM_DailyAgentSpend"
ADD COLUMN "response_time_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "response_time_count" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN "ttft_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ttft_count" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "LiteLLM_DailyTeamSpend"
ADD COLUMN "response_time_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "response_time_count" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN "ttft_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ttft_count" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "LiteLLM_DailyTagSpend"
ADD COLUMN "response_time_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "response_time_count" BIGINT NOT NULL DEFAULT 0,
ADD COLUMN "ttft_ms_sum" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "ttft_count" BIGINT NOT NULL DEFAULT 0;
